#submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=LHEHTsm600 --leptonSelection=none --samples=TTJets_SingleLeptonFromT"
#submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=LHEHTsm600 --leptonSelection=none --samples=TTJets_SingleLeptonFromTbar"
#submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=LHEHTsm600 --leptonSelection=none --samples=TTJets_DiLepton"
#submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=LHEHTg600 --leptonSelection=none --samples=TTJets_LO_HT600to800_ext"
#submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=LHEHTg600 --leptonSelection=none --samples=TTJets_LO_HT800to1200_ext"
#submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=LHEHTg600 --leptonSelection=none --samples=TTJets_LO_HT1200to2500_ext"
#submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=LHEHTg600 --leptonSelection=none --samples=TTJets_LO_HT2500toInf"
#
#submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=HT500 --leptonSelection=none --samples=WJetsToLNu_HT200to400"
#submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=HT500 --leptonSelection=none --samples=WJetsToLNu_HT400to600"
#submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=HT500 --leptonSelection=none --samples=WJetsToLNu_HT600to800"
#submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=HT500 --leptonSelection=none --samples=WJetsToLNu_HT800to1200"
#submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=HT500 --leptonSelection=none --samples=WJetsToLNu_HT1200to2500"
#submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=HT500 --leptonSelection=none --samples=WJetsToLNu_HT2500toInf"
#
#submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=HT500 --leptonSelection=none --samples=ST_s_channel_4f_leptonDecays"
#submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=HT500 --leptonSelection=none --samples=ST_t_channel_antitop_4f_leptonDecays"
#submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=HT500 --leptonSelection=none --samples=ST_t_channel_top_4f_leptonDecays"
#submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=HT500 --leptonSelection=none --samples=ST_tW_antitop_5f_NoFullyHadronicDecays"
#submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=HT500 --leptonSelection=none --samples=ST_tW_top_5f_NoFullyHadronicDecays"
#
#submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=HT500 --leptonSelection=none --samples=TTWToLNu"
#submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=HT500 --leptonSelection=none --samples=TTWToQQ"
#submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=HT500 --leptonSelection=none --samples=TTZToLLNuNu"
#submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=HT500 --leptonSelection=none --samples=TTZToQQ"
#
##Diboson still missing
#
#submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=HT500 --leptonSelection=none --samples=QCD_HT300to500"
#submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=HT500 --leptonSelection=none --samples=QCD_HT500to700"
#submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=HT500 --leptonSelection=none --samples=QCD_HT700to1000"
#submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=HT500 --leptonSelection=none --samples=QCD_HT1000to1500"
#submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=HT500 --leptonSelection=none --samples=QCD_HT1500to2000"
#submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=HT500 --leptonSelection=none --samples=QCD_HT2000toInf"
#
#submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=HT500 --leptonSelection=none --samples=DYJetsToLL_M50_HT100to200"
#submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=HT500 --leptonSelection=none --samples=DYJetsToLL_M50_HT200to400"
#submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=HT500 --leptonSelection=none --samples=DYJetsToLL_M50_HT400to600"
#submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=HT500 --leptonSelection=none --samples=DYJetsToLL_M50_HT400to600"
#submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=HT500 --leptonSelection=none --samples=DYJetsToLL_M50_HT600toInf"
#
#
submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=eleDataSet --leptonSelection=none --samples=SingleElectron_Run2016B_23Sep2016"
submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=eleDataSet --leptonSelection=none --samples=SingleElectron_Run2016C_23Sep2016_v1"
submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=eleDataSet --leptonSelection=none --samples=SingleElectron_Run2016D_23Sep2016_v1"
submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=eleDataSet --leptonSelection=none --samples=SingleElectron_Run2016E_23Sep2016_v1"
submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=eleDataSet --leptonSelection=none --samples=SingleElectron_Run2016F_23Sep2016_v1"
submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=eleDataSet --leptonSelection=none --samples=SingleElectron_Run2016G_23Sep2016_v1"
submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=eleDataSet --leptonSelection=none --samples=SingleElectron_Run2016H_PromptReco_v2"
submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=eleDataSet --leptonSelection=none --samples=SingleElectron_Run2016H_PromptReco_v3"

submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=muDataSet --leptonSelection=none --samples=SingleMuon_Run2016B_23Sep2016"
submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=muDataSet --leptonSelection=none --samples=SingleMuon_Run2016C_23Sep2016_v1"
submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=muDataSet --leptonSelection=none --samples=SingleMuon_Run2016D_23Sep2016_v1"
submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=muDataSet --leptonSelection=none --samples=SingleMuon_Run2016E_23Sep2016_v1"
submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=muDataSet --leptonSelection=none --samples=SingleMuon_Run2016F_23Sep2016_v1"
submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=muDataSet --leptonSelection=none --samples=SingleMuon_Run2016G_23Sep2016_v1"
submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=muDataSet --leptonSelection=none --samples=SingleMuon_Run2016H_PromptReco_v2"
submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=muDataSet --leptonSelection=none --samples=SingleMuon_Run2016H_PromptReco_v3"

submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=metDataSet --leptonSelection=none --samples=MET_Run2016B_23Sep2016"
submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=metDataSet --leptonSelection=none --samples=MET_Run2016C_23Sep2016_v1"
submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=metDataSet --leptonSelection=none --samples=MET_Run2016D_23Sep2016_v1"
submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=metDataSet --leptonSelection=none --samples=MET_Run2016E_23Sep2016_v1"
submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=metDataSet --leptonSelection=none --samples=MET_Run2016F_23Sep2016_v1"
submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=metDataSet --leptonSelection=none --samples=MET_Run2016G_23Sep2016_v1"
submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=metDataSet --leptonSelection=none --samples=MET_Run2016H_PromptReco_v2"
submitBatch.py --title='1l_PP' "python cmgPostProcessingAntiSelectionV2.py --overwrite --skim=metDataSet --leptonSelection=none --samples=MET_Run2016H_PromptReco_v3"

