#python cmgPostProcessing.py --overwrite  --skim="eleDataSet"  --samples=SingleElectron_Run2016B_23Sep2016
#python cmgPostProcessing.py --overwrite  --skim="eleDataSet"  --samples=SingleElectron_Run2016C_23Sep2016_v1
#python cmgPostProcessing.py --overwrite  --skim="eleDataSet"  --samples=SingleElectron_Run2016D_23Sep2016_v1
#python cmgPostProcessing.py --overwrite  --skim="eleDataSet"  --samples=SingleElectron_Run2016E_23Sep2016_v1
#python cmgPostProcessing.py --overwrite  --skim="eleDataSet"  --samples=SingleElectron_Run2016F_23Sep2016_v1
#python cmgPostProcessing.py --overwrite  --skim="eleDataSet"  --samples=SingleElectron_Run2016G_23Sep2016_v1
#python cmgPostProcessing.py --overwrite  --skim="eleDataSet"  --samples=SingleElectron_Run2016H_PromptReco_v2
#python cmgPostProcessing.py --overwrite  --skim="eleDataSet"  --samples=SingleElectron_Run2016H_PromptReco_v3
#python cmgPostProcessing.py --overwrite  --skim="muDataSet"  --samples=SingleMuon_Run2016B_23Sep2016
#python cmgPostProcessing.py --overwrite  --skim="muDataSet"  --samples=SingleMuon_Run2016C_23Sep2016_v1
#python cmgPostProcessing.py --overwrite  --skim="muDataSet"  --samples=SingleMuon_Run2016D_23Sep2016_v1
#python cmgPostProcessing.py --overwrite  --skim="muDataSet"  --samples=SingleMuon_Run2016E_23Sep2016_v1
#python cmgPostProcessing.py --overwrite  --skim="muDataSet"  --samples=SingleMuon_Run2016F_23Sep2016_v1
#python cmgPostProcessing.py --overwrite  --skim="muDataSet"  --samples=SingleMuon_Run2016G_23Sep2016_v1
#python cmgPostProcessing.py --overwrite  --skim="muDataSet"  --samples=SingleMuon_Run2016H_PromptReco_v2
#python cmgPostProcessing.py --overwrite  --skim="muDataSet"  --samples=SingleMuon_Run2016H_PromptReco_v3
python cmgPostProcessing.py --overwrite  --skim=""  --samples=MET_Run2016B_23Sep2016
python cmgPostProcessing.py --overwrite  --skim=""  --samples=MET_Run2016C_23Sep2016_v1
python cmgPostProcessing.py --overwrite  --skim=""  --samples=MET_Run2016D_23Sep2016_v1
python cmgPostProcessing.py --overwrite  --skim=""  --samples=MET_Run2016E_23Sep2016_v1
python cmgPostProcessing.py --overwrite  --skim=""  --samples=MET_Run2016F_23Sep2016_v1
python cmgPostProcessing.py --overwrite  --skim=""  --samples=MET_Run2016G_23Sep2016_v1
python cmgPostProcessing.py --overwrite  --skim=""  --samples=MET_Run2016H_PromptReco_v2
python cmgPostProcessing.py --overwrite  --skim=""  --samples=MET_Run2016H_PromptReco_v3
