python cmgPostProcessing.py --overwrite  --skim=""  --samples=SingleElectron_Run2016B
python cmgPostProcessing.py --overwrite  --skim=""  --samples=SingleElectron_Run2016C
python cmgPostProcessing.py --overwrite  --skim=""  --samples=SingleElectron_Run2016D
python cmgPostProcessing.py --overwrite  --skim=""  --samples=SingleElectron_Run2016E
python cmgPostProcessing.py --overwrite  --skim=""  --samples=SingleElectron_Run2016F
python cmgPostProcessing.py --overwrite  --skim=""  --samples=SingleElectron_Run2016G
python cmgPostProcessing.py --overwrite  --skim=""  --samples=SingleElectron_Run2016H_v2
python cmgPostProcessing.py --overwrite  --skim=""  --samples=SingleElectron_Run2016H_v3
python cmgPostProcessing.py --overwrite  --skim=""  --samples=SingleMuon_Run2016B
python cmgPostProcessing.py --overwrite  --skim=""  --samples=SingleMuon_Run2016C
python cmgPostProcessing.py --overwrite  --skim=""  --samples=SingleMuon_Run2016D
python cmgPostProcessing.py --overwrite  --skim=""  --samples=SingleMuon_Run2016E
python cmgPostProcessing.py --overwrite  --skim=""  --samples=SingleMuon_Run2016F
python cmgPostProcessing.py --overwrite  --skim=""  --samples=SingleMuon_Run2016G
python cmgPostProcessing.py --overwrite  --skim=""  --samples=SingleMuon_Run2016H_v2
python cmgPostProcessing.py --overwrite  --skim=""  --samples=SingleMuon_Run2016H_v3
python cmgPostProcessing.py --overwrite  --skim=""  --samples=MET_Run2016B
python cmgPostProcessing.py --overwrite  --skim=""  --samples=MET_Run2016C
python cmgPostProcessing.py --overwrite  --skim=""  --samples=MET_Run2016D
python cmgPostProcessing.py --overwrite  --skim=""  --samples=MET_Run2016E
python cmgPostProcessing.py --overwrite  --skim=""  --samples=MET_Run2016F
python cmgPostProcessing.py --overwrite  --skim=""  --samples=MET_Run2016G
python cmgPostProcessing.py --overwrite  --skim=""  --samples=MET_Run2016H_v2
python cmgPostProcessing.py --overwrite  --skim=""  --samples=MET_Run2016H_v3
