cfg="nanoAOD_v0"
generalTag="nanoAOD-test"
cuts="bins_mtct_sum"
sigOpt="NoSig" #t2tt bm
lepCol="Lepton"
jetCol="JetClean"
tauCol="TauClean"
lepThresh="def"
jetThresh="def"
nanoAOD="--nanoAOD"
ppSet="nanoAOD_v6_0-0"
year="2016"
skim="preIncLep"
bkgs="ttx vv qcd st z dy tt_1l tt_2l w"
dataset="MET"
postFuncs="fakeEstimate"
redoYields="" #--redo_yields
[ ! -z "$dataset" ] && getData="--getData"

# central
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr             --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs $bkgs --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep lep --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields --postFuncs $postFuncs
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr             --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs $bkgs --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep mu  --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr             --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs $bkgs --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep el  --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields

# isr_Wpt
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts --weights prompt trig_eff lepSF pu isr_nIsr                     --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs $bkgs --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep lep --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields --postFuncs $postFuncs
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts --weights prompt trig_eff lepSF pu isr_nIsr                     --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs $bkgs --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep mu  --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts --weights prompt trig_eff lepSF pu isr_nIsr                     --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs $bkgs --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep el  --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields

# isr_nIsr
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts --weights prompt trig_eff lepSF pu isr_Wpt                      --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs $bkgs --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep lep --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields --postFuncs $postFuncs
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts --weights prompt trig_eff lepSF pu isr_Wpt                      --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs $bkgs --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep mu  --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts --weights prompt trig_eff lepSF pu isr_Wpt                      --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs $bkgs --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep el  --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields

# pu down
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts --weights prompt trig_eff lepSF pu_down isr_Wpt isr_nIsr        --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs $bkgs --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep lep --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields --postFuncs $postFuncs
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts --weights prompt trig_eff lepSF pu_down isr_Wpt isr_nIsr        --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs $bkgs --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep mu  --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts --weights prompt trig_eff lepSF pu_down isr_Wpt isr_nIsr        --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs $bkgs --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep el  --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields

# pu up
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts --weights prompt trig_eff lepSF pu_up isr_Wpt isr_nIsr          --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs $bkgs --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep lep --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields --postFuncs $postFuncs
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts --weights prompt trig_eff lepSF pu_up isr_Wpt isr_nIsr          --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs $bkgs --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep mu  --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts --weights prompt trig_eff lepSF pu_up isr_Wpt isr_nIsr          --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs $bkgs --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep el  --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields

# b_l_down
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr sf_l_down   --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs $bkgs --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep lep --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields --postFuncs $postFuncs
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr sf_l_down   --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs $bkgs --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep mu  --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr sf_l_down   --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs $bkgs --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep el  --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields

# b_l_up
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr sf_l_up     --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs $bkgs --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep lep --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields --postFuncs $postFuncs
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr sf_l_up     --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs $bkgs --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep mu  --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr sf_l_up     --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs $bkgs --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep el  --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields

# b_b_down
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr sf_b_down   --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs $bkgs --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep lep --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields --postFuncs $postFuncs
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr sf_b_down   --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs $bkgs --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep mu  --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr sf_b_down   --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs $bkgs --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep el  --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields

# b_b_up
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr sf_b_up     --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs $bkgs --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep lep --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields --postFuncs $postFuncs
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr sf_b_up     --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs $bkgs --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep mu  --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr sf_b_up     --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs $bkgs --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep el  --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields

# jec
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr jec_central --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs $bkgs --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep lep --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields --postFuncs $postFuncs
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr jec_central --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs $bkgs --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep mu  --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr jec_central --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs $bkgs --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep el  --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields

python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr jec_up      --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs $bkgs --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep lep --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields --postFuncs $postFuncs
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr jec_up      --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs $bkgs --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep mu  --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr jec_up      --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs $bkgs --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep el  --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields

python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr jec_down    --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs $bkgs --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep lep --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields --postFuncs $postFuncs
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr jec_down    --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs $bkgs --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep mu  --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr jec_down    --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs $bkgs --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep el  --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields

# jer
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr jer_central --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs $bkgs --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep lep --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields --postFuncs $postFuncs
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr jer_central --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs $bkgs --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep mu  --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr jer_central --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs $bkgs --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep el  --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields

python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr jer_up      --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs $bkgs --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep lep --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields --postFuncs $postFuncs
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr jer_up      --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs $bkgs --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep mu  --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr jer_up      --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs $bkgs --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep el  --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields

python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr jer_down    --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs $bkgs --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep lep --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields --postFuncs $postFuncs
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr jer_down    --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs $bkgs --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep mu  --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr jer_down    --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs $bkgs --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep el  --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields

##
## Sig Systs
## 

# central
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr                   --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs vv --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep lep --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields --postFuncs $postFuncs

# isr
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts"_sig" --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr noisrsig          --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs vv --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep lep --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields --postFuncs $postFuncs
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts"_sig" --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr noisrsig          --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs vv --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep mu  --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts"_sig" --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr noisrsig          --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs vv --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep el  --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields

# btag fs up
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts"_sig" --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr sf_fs_up          --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs vv --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep lep --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields --postFuncs $postFuncs
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts"_sig" --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr sf_fs_up          --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs vv --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep mu  --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts"_sig" --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr sf_fs_up          --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs vv --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep el  --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields

# btag fs down
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts"_sig" --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr sf_fs_down        --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs vv --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep lep --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields --postFuncs $postFuncs
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts"_sig" --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr sf_fs_down        --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs vv --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep mu  --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts"_sig" --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr sf_fs_down        --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs vv --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep el  --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields

# genmet
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts"_sig" --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr genmet            --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs vv --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep lep --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields --postFuncs $postFuncs
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts"_sig" --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr genmet            --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs vv --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep mu  --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts"_sig" --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr genmet            --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs vv --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep el  --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields

# Q2
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts"_sig" --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr Q2central_central --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs vv --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep lep --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields --postFuncs $postFuncs
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts"_sig" --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr Q2central_up      --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs vv --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep mu  --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts"_sig" --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr Q2central_down    --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs vv --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep el  --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields

python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts"_sig" --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr Q2up_central      --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs vv --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep lep --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields --postFuncs $postFuncs
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts"_sig" --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr Q2up_down         --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs vv --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep el  --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields
#python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts"_sig" --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr Q2up_up           --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs vv --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep mu  --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields

python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts"_sig" --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr Q2down_central    --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs vv --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep lep --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields --postFuncs $postFuncs
python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts"_sig" --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr Q2down_up         --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs vv --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep mu  --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields
#python $CMSSW_BASE/src/Workspace/DegenerateStopAnalysis/python/scripts/degStop.py --cfg $cfg --task yields --cuts $cuts"_sig" --weights prompt trig_eff lepSF pu isr_Wpt isr_nIsr Q2down_down       --generalTag $generalTag --ppSet $ppSet $nanoAOD --skim $skim --year $year $getData --sigOpt $sigOpt --bkgs vv --lepCol $lepCol --jetCol $jetCol --tauCol $tauCol --lep el  --jetThresh $jetThresh --lepThresh $lepThresh --nProc 10 $redoYields
