import ROOT
from localInfo import username

def DrawClosure(plot1,plot2,plot3,plot4,plot1name,xaxis,path):

  can = ROOT.TCanvas("c",plot1name,800,800)
  Pad1 = ROOT.TPad("Pad1", "Pad1", 0, 0.3, 1, 1.0)
  Pad1.SetLogy()
  Pad1.SetBottomMargin(0)
  Pad1.SetGridx()
  Pad1.Draw()
  Pad1.cd()
  #text = ROOT.TLatex()
  #text.DrawLatex(0.15,0.93, plot1name+" #sqrt{s} = 13 TeV")
  plot1.SetTitle(plot1name)
  plot1.SetTitleSize(5)
  plot1.SetStats(0)
  plot1.SetLineColor(ROOT.kBlack)
  plot1.SetLineWidth(2)
  plot1.SetAxisRange(0.1,(plot1.GetMaximum())*(plot1.GetMaximum())*2,"Y")
  plot1.Draw()
  plot2.SetStats(0)
  plot2.SetLineColor(ROOT.kRed+1)
  plot2.SetLineWidth(2)
  plot2.Draw('same')
  plot3.SetStats(0)
  plot3.SetLineColor(ROOT.kAzure+10)
  plot3.SetLineStyle(2)
  plot3.Draw('same')
  plot4.SetStats(0)
  plot4.SetLineColor(ROOT.kAzure)
  plot4.SetLineStyle(2)
  plot4.Draw('same')
  plot4.GetYaxis().SetLabelSize(0.)
  plot1.GetYaxis().SetTitle("# of Events")
  plot1.GetYaxis().SetTitleSize(20)
  plot1.GetYaxis().SetTitleFont(43)
  plot1.GetYaxis().SetTitleOffset(1.55)
  plot1.GetYaxis().SetLabelFont(43)
  plot1.GetYaxis().SetLabelSize(15)
  leg = ROOT.TLegend(0.7,0.7,0.9,0.9)
  leg.AddEntry(plot2, "Predicted","l")
  leg.AddEntry(plot1, "Truth","l")
  leg.AddEntry(plot3, "1.1*(Eff) Pred","l")
  leg.AddEntry(plot4, "0.9*(Eff) Pred","l")
  leg.SetFillColor(0)
  leg.Draw()
  can.cd()
  Pad2 = ROOT.TPad("Pad2", "Pad2",  0, 0.05, 1, 0.3)
  Pad2.SetTopMargin(0)
  Pad2.SetBottomMargin(0.2)
  Pad2.SetGridx()
  Pad2.Draw()
  Pad2.cd()
  Func = ROOT.TF1('Func',"[0]",plot1.GetXaxis().GetXmin(),plot1.GetXaxis().GetXmax())
  Func.SetParameter(0,1)
  Func.SetLineColor(2)
  h_ratio = plot1.Clone("h_ratio")
  h_ratio.SetLineColor(ROOT.kBlack)
  h_ratio.SetLineWidth(2)
  h_ratio.SetMinimum(0.0)
  h_ratio.SetMaximum(2.0)
  h_ratio.Sumw2()
  h_ratio.SetStats(0)
  h_ratio.Divide(plot2)
  h_ratio.SetMarkerStyle(21)
  #h_ratio.SetMarkerSize(0.5)
  h_ratio.Draw("ep")
  Func.Draw('same')
  h_ratio.SetTitle("")
  h_ratio.GetYaxis().SetTitle("Truth/Pred ")
  h_ratio.GetYaxis().SetNdivisions(505)
  h_ratio.GetYaxis().SetTitleSize(20)
  h_ratio.GetYaxis().SetTitleFont(43)
  h_ratio.GetYaxis().SetTitleOffset(1.55)
  h_ratio.GetYaxis().SetLabelFont(43)
  h_ratio.GetYaxis().SetLabelSize(15)
  h_ratio.GetXaxis().SetTitle(xaxis)
  h_ratio.GetXaxis().SetTitleSize(20)
  h_ratio.GetXaxis().SetTitleFont(43)
  h_ratio.GetXaxis().SetTitleOffset(4.)
  h_ratio.GetXaxis().SetLabelFont(43)
  h_ratio.GetXaxis().SetLabelSize(15)
  can.SetGridx()
  #can.Update()
  can.SaveAs(path)


                                                                
