import ROOT
from localInfo import username
from math import *

def DrawClosure(plot1,plot2,plot3,xaxis,path):

  eplus = plot2.Clone("eplus")                                                                                                                              
  eminus = plot2.Clone("minus") 
  for i in range(plot2.GetNbinsX()):
    err = sqrt((plot3.GetBinContent(i) - plot2.GetBinContent(i))**2+plot2.GetBinError(i)**2)
    eplus.SetBinContent(i,plot2.GetBinContent(i)+err)
    eminus.SetBinContent(i,plot2.GetBinContent(i)-err)

  #ROOT.setTDRStyle()
  can = ROOT.TCanvas("c",xaxis,600,600)
  can.cd()
  latex1 = ROOT.TLatex()
  latex1.SetNDC()
  latex1.SetTextSize(0.035)
  latex1.SetTextAlign(11) # align right
  latex2 = ROOT.TLatex()
  latex2.SetNDC()
  latex2.SetTextSize(0.035)
  latex2.SetTextAlign(11) # align left
  latex2.DrawLatex(0.16,0.9,"CMS Simulation")
  latex1.DrawLatex(0.7,0.9,"L=4 fb^{-1} (13 TeV)")
  Pad1 = ROOT.TPad("Pad1", "Pad1", 0, 0.35, 1, 0.9)
  Pad1.SetLogy()
  Pad1.SetTopMargin(0.02)
  Pad1.SetBottomMargin(0)
  Pad1.SetLeftMargin(0.16)
  Pad1.SetRightMargin(0.05)
  #Pad1.SetTickY(1)
  #Pad1.SetGridx()
  Pad1.Draw()
  Pad1.cd()
  #text = ROOT.TLatex()
  #text.DrawLatex(0.15,0.93, plot1name+" #sqrt{s} = 13 TeV")
  eplus.SetTitle("")
  eplus.SetAxisRange(0.0101,(plot1.GetMaximum())*(plot1.GetMaximum())*100,"Y")
  eplus.SetStats(0)
  eplus.SetLineColor(ROOT.kAzure)
  #eplus.SetFillColor(ROOT.kGray)
  #eplus.SetMarkerColor(ROOT.kAzure)
  eplus.SetMarkerSize(0.1)
  eplus.SetLineWidth(2)
  eplus.GetXaxis().SetLabelSize(0.)
  eplus.Draw('HIST')
  eminus.SetStats(0)
  #eminus.SetFillColor(10)
  eminus.SetLineColor(ROOT.kAzure)
  #eminus.SetMarkerColor(ROOT.kAzure)
  eminus.GetXaxis().SetLabelSize(0.)
  eminus.SetMarkerSize(0.1)
  eminus.SetLineWidth(2)
  eminus.Draw('HISTsame')
  #plot1.SetTitleSize(5)
  plot1.SetStats(0)
  plot1.SetLineColor(ROOT.kBlack)
  plot1.SetLineColor(ROOT.kBlack)
  plot1.SetMarkerColor(ROOT.kBlack)
  plot1.SetMarkerSize(0.6)
  plot1.SetLineWidth(2)
  plot1.Draw('eh1same')
  plot2.SetStats(0)
  plot2.SetLineColor(ROOT.kRed+1)
  plot2.SetMarkerColor(ROOT.kRed+1)
  plot2.SetMarkerSize(0.6)
  plot2.SetLineWidth(2)
  plot2.Draw('HISTsame')
  #eminus.GetYaxis().SetLabelSize(0.)
  #eplus.GetYaxis().SetTitle("Number of Events / 50 GeV")
  eplus.GetYaxis().SetTitle("Number of Events / Bin ")
  eplus.GetYaxis().SetTitleSize(0.08)
  #plot1.GetYaxis().SetTitleFont(43)
  eplus.GetYaxis().SetTitleOffset(0.7)
  #eplus.GetYaxis().SetLabelFont(43)
  eplus.GetYaxis().SetLabelSize(0.08)
  leg = ROOT.TLegend(0.6,0.65,0.95,0.98)
  leg.AddEntry(plot2, "Prediction")
  leg.AddEntry(plot1, "MC truth")
  leg.AddEntry(eplus, "#pm 10% sys + stat")
  #leg.AddEntry(eminus, "0.9*(Eff) Pred","l")
  leg.SetTextSize(0.06)
  leg.SetFillColor(0)
  leg.SetShadowColor( ROOT.kWhite )
  leg.SetBorderSize( 0 )
  leg.SetBorderSize( 1 )
  leg.Draw()
  can.cd()
  Pad2 = ROOT.TPad("Pad2", "Pad2",  0, 0.05, 1, 0.35)
  Pad2.SetTopMargin(0)
  Pad2.SetBottomMargin(0.4)
  Pad2.SetLeftMargin(0.16)
  Pad2.SetRightMargin(0.05)
  #Pad2.SetTickX(1)
  #Pad2.SetTickY(1)
  #Pad2.SetGridx()
  Pad2.Draw()
  Pad2.cd()
  #ROOT.setTDRStyle()
  #ROOT.setTDRStyle()
  Func = ROOT.TF1('Func',"[0]",plot1.GetXaxis().GetXmin(),plot1.GetXaxis().GetXmax())
  Func.SetParameter(0,1)
  Func.SetLineColor(2)
  h_ratio = plot2.Clone("h_ratio")
  h_ratio.SetLineColor(ROOT.kRed+1)
  h_ratio.SetLineWidth(2)
  h_ratio.SetMinimum(0.0)
  h_ratio.SetMaximum(1.99)
  h_ratio.Sumw2()
  h_ratio.SetStats(0)
  h_ratio.Divide(plot1)
  h_ratio.SetMarkerStyle(21)
  h_ratio.SetMarkerColor(ROOT.kRed+1)
  h_ratio.SetMarkerSize(0.7)
  #h_ratio.SetTitle(";;Truth/Pred;")
  h_ratio.SetTitle("")
  h_ratio.GetYaxis().SetTitle("Pred/Sim ")
  h_ratio.GetYaxis().SetNdivisions(505)
  h_ratio.GetXaxis().SetNdivisions(505)
  h_ratio.GetYaxis().SetTitleSize(0.15)   #0.12
  h_ratio.GetYaxis().SetTitleFont(42)
  h_ratio.GetYaxis().SetTitleOffset(0.38)
  #h_ratio.GetYaxis().SetLabelFont(43)
  h_ratio.GetYaxis().SetLabelSize(0.15)
  print xaxis
  #h_ratio.GetXaxis().SetTitle(xaxis+"(GeV)")
  #h_ratio.GetXaxis().SetNdivisions(505)
  h_ratio.GetXaxis().SetTitle(xaxis)
  h_ratio.GetXaxis().SetTitleSize(0.2) #0.12
  h_ratio.GetXaxis().SetTitleFont(42)
  h_ratio.GetXaxis().SetTitleOffset(0.8)  # 0.9
  #h_ratio.GetXaxis().SetLabelFont(43)
  h_ratio.GetXaxis().SetLabelSize(0.17)
  h_ratio.Draw("eh1")
  Func.Draw("same")
  #can.SetGridx()
  #Pad2.Update()
  #can.Update()
  #can.Draw()
  can.SaveAs(path)

