#!/bin/sh
python convert.py --samples=ttJetsCSA14     --chmode=$1 $2 --fromPercentage=0   --toPercentage=5 &
python convert.py --samples=ttJetsCSA14     --chmode=$1 $2 --fromPercentage=5   --toPercentage=10 &
python convert.py --samples=ttJetsCSA14     --chmode=$1 $2 --fromPercentage=10  --toPercentage=15 &
python convert.py --samples=ttJetsCSA14     --chmode=$1 $2 --fromPercentage=15  --toPercentage=20 &
python convert.py --samples=ttJetsCSA14     --chmode=$1 $2 --fromPercentage=20  --toPercentage=25 &
python convert.py --samples=ttJetsCSA14     --chmode=$1 $2 --fromPercentage=25  --toPercentage=30 &
python convert.py --samples=ttJetsCSA14     --chmode=$1 $2 --fromPercentage=30  --toPercentage=35 &
python convert.py --samples=ttJetsCSA14     --chmode=$1 $2 --fromPercentage=35  --toPercentage=40 &
python convert.py --samples=ttJetsCSA14     --chmode=$1 $2 --fromPercentage=40  --toPercentage=45 &
python convert.py --samples=ttJetsCSA14     --chmode=$1 $2 --fromPercentage=45  --toPercentage=50 &
python convert.py --samples=ttJetsCSA14     --chmode=$1 $2 --fromPercentage=50  --toPercentage=55 &
python convert.py --samples=ttJetsCSA14     --chmode=$1 $2 --fromPercentage=55  --toPercentage=60 &
python convert.py --samples=ttJetsCSA14     --chmode=$1 $2 --fromPercentage=60  --toPercentage=65 &
python convert.py --samples=ttJetsCSA14     --chmode=$1 $2 --fromPercentage=65  --toPercentage=70 &
python convert.py --samples=ttJetsCSA14     --chmode=$1 $2 --fromPercentage=70  --toPercentage=75 &
python convert.py --samples=ttJetsCSA14     --chmode=$1 $2 --fromPercentage=75  --toPercentage=80 &
python convert.py --samples=ttJetsCSA14     --chmode=$1 $2 --fromPercentage=80  --toPercentage=85 &
python convert.py --samples=ttJetsCSA14     --chmode=$1 $2 --fromPercentage=85  --toPercentage=90 &
python convert.py --samples=ttJetsCSA14     --chmode=$1 $2 --fromPercentage=90  --toPercentage=95 &
python convert.py --samples=ttJetsCSA14     --chmode=$1 $2 --fromPercentage=95  --toPercentage=100 &
