import ROOT
from stage2Tuples import ttJetsCSA1450ns , ttJetsCSA1425ns
from localInfo import username


def getMu(c,j):
  muIsGlobal = c.GetLeaf('muIsGlobal').GetValue(j)
  muIsTracker = c.GetLeaf('muIsTracker').GetValue(j)
  dz = c.GetLeaf('muDz').GetValue(j)
  pt = c.GetLeaf('muPt').GetValue(j)
  eta= c.GetLeaf('muEta').GetValue(j)
  phi= c.GetLeaf('muPhi').GetValue(j)
  Pdg= c.GetLeaf('gLepPdg').GetValue(j)
  gLepDR = c.GetLeaf('gLepDR').GetValue(j)
  RelIso = c.GetLeaf('muRelIso').GetValue(j)
  ChargedHadronPt = c.GetLeaf('muIso03sumChargedHadronPt').GetValue(j)
  NeutralHadronEt = c.GetLeaf('muIso03sumNeutralHadronEt').GetValue(j)
  PhotonEt = c.GetLeaf('muIso03sumPhotonEt').GetValue(j)
  PUChargedHadronPt = c.GetLeaf('muIso03sumPUChargedHadronPt').GetValue(j)
  RelIsoPred = (ChargedHadronPt+max(0,(NeutralHadronEt+PhotonEt-(0.5*PUChargedHadronPt))))/pt
  cand={'RelIsoPred':RelIsoPred, 'ChargedHadronPt':ChargedHadronPt,'NeutralHadronEt':NeutralHadronEt,'PhotonEt':PhotonEt,'PUChargedHadronPt':PUChargedHadronPt,'muIsGlobal':muIsGlobal, 'muIsTracker':muIsTracker, 'dz':dz, 'pt':pt, 'eta':eta, 'phi':phi, 'Pdg':Pdg, 'gLepDR':gLepDR, 'RelIso':RelIso}
  #if pt>5 and (muIsGlobal or  muIsTracker) and abs(eta)<2.5 and abs(dz)< 0.5 and gLepDR<0.5:
  if pt>5 and abs(eta)<2.5 and abs(dz)<0.5 and (muIsGlobal or  muIsTracker):
   return cand

File = ROOT.TFile('IsolationStudy.Root','RECREATE')
h_RelIso50 = ROOT.TH1F('muRelIso', 'muRelIso',100,0,1)
h_RelIso25 = ROOT.TH1F('muRelIso', 'muRelIso',100,0,1)
h_RelIso50Pred = ROOT.TH1F('muRelIsoPred', 'muRelIsoPred',100,0,1)
h_RelIso25Pred = ROOT.TH1F('muRelIsoPred', 'muRelIsoPred',100,0,1)
h_ChargedHadronPt50 = ROOT.TH1F('muIso03sumChargedHadronPt', 'muIso03sumChargedHadronPt', 100, 0, 1)
h_NeutralHadronEt50 = ROOT.TH1F('muIso03sumNeutralHadronEt', 'muIso03sumNeutralHadronEt', 100, 0, 1)
h_PhotonEt50 = ROOT.TH1F('muIso03sumPhotonEt', 'muIso03sumPhotonEt', 100, 0, 1)
h_PUChargedHadronPt50 = ROOT.TH1F('muIso03sumPUChargedHadronPt', 'muIso03sumPUChargedHadronPt', 100, 0, 1)
h_ChargedHadronPt25 = ROOT.TH1F('muIso03sumChargedHadronPt', 'muIso03sumChargedHadronPt', 100, 0, 1)
h_NeutralHadronEt25 = ROOT.TH1F('muIso03sumNeutralHadronEt', 'muIso03sumNeutralHadronEt', 100, 0, 1)
h_PhotonEt25 = ROOT.TH1F('muIso03sumPhotonEt', 'muIso03sumPhotonEt', 100, 0, 1)
h_PUChargedHadronPt25 = ROOT.TH1F('muIso03sumPUChargedHadronPt', 'muIso03sumPUChargedHadronPt', 100, 0, 1)

c50 = ROOT.TChain('Events')
#for b in ttJetsCSA1450ns['bins']:
#  c.Add(ttJetsCSA1450ns['dirname']+'/'+b+'/h*.root')
c50.Add('/data/easilar/convertedTuples_v23/copyMET/ttJetsCSA1450ns/histo_ttJetsCSA1450ns_from0To10.root')

c25 = ROOT.TChain('Events')
#for b in ttJetsCSA1425ns['bins']:
#  c2.Add(ttJetsCSA1425ns['dirname']+'/'+b+'/h*.root')
c25.Add('/data/easilar/convertedTuples_v23/copyMET_DR0.4/ttJetsCSA1425ns/histo_ttJetsCSA1425ns_from0To10.root')

number_events50 = c50.GetEntries()
print number_events50
for i in range(number_events50):
  c50.GetEntry(i)
  nmuons = c50.GetLeaf('nmuCount').GetValue()
  for mu in range(int(nmuons)):
    muons50 = getMu(c50,mu)
    if muons50['gLepDR']<0.5 and muons50['Pdg']:
      print "fiiling 50ns hist..."
      h_RelIso50.Fill(muons50['RelIso'])
      h_ChargedHadronPt50.Fill(muons50['ChargedHadronPt'])
      h_NeutralHadronEt50.Fill(muons50['NeutralHadronEt'])
      h_PhotonEt50.Fill(muons50['PhotonEt'])
      h_PUChargedHadronPt50.Fill(muons50['PUChargedHadronPt'])
      h_RelIso50Pred.Fill(muons50['RelIsoPred'])


number_events25 = c25.GetEntries()
print number_events25
for i in range(number_events25):
  c25.GetEntry(i)
  nmuons = c25.GetLeaf('nmuCount').GetValue()
  for mu in range(int(nmuons)):
    muons25 = getMu(c25,mu)
    if muons25['gLepDR']<0.5 and muons25['Pdg']:
      h_RelIso25.Fill(muons25['RelIso'])
      h_ChargedHadronPt25.Fill(muons25['ChargedHadronPt'])
      h_NeutralHadronEt25.Fill(muons25['NeutralHadronEt'])
      h_PhotonEt25.Fill(muons25['PhotonEt'])
      h_PUChargedHadronPt25.Fill(muons25['PUChargedHadronPt'])
      h_RelIso25Pred.Fill(muons25['RelIsoPred'])
     
File.cd()

can = ROOT.TCanvas('RelIso Comp 50_25')
can.cd()
h_RelIso50.SetLineColor(ROOT.kRed)   ## 1:50ns  , 2:25ns
#h_RelIso50.Scale(1/h_RelIso50.Integral())
h_RelIso50.SetLineWidth(2)
h_RelIso50.Draw()
#h_RelIso25.Scale(h_RelIso50.Integral()/h_RelIso25.Integral())
h_RelIso25.SetLineColor(ROOT.kBlue)
h_RelIso25.SetLineWidth(2)
h_RelIso25.Draw('same')
#can.SetLogy()
#can.Print('/afs/hephy.at/user/e/easilar/www/LastCSA14/MuonRelIsoComp25_50.png')
#can.Delete()
leg = ROOT.TLegend(0.6,0.6,0.9,0.7)
leg.AddEntry(h_RelIso50, "50ns","l")
leg.AddEntry(h_RelIso25, "25ns","l")
leg.SetFillColor(0)
leg.Draw()
can.Update()
can.Write()
#can.Close()

can1 = ROOT.TCanvas('ChargedHadronPt Comp 50_25')
can1.cd()
h_ChargedHadronPt25.SetLineColor(ROOT.kBlue)
h_ChargedHadronPt25.Draw()
h_ChargedHadronPt50.SetLineColor(ROOT.kRed)
h_ChargedHadronPt50.SetLineWidth(2)
h_ChargedHadronPt50.Draw('same')
#can1.Print('/afs/hephy.at/user/e/easilar/www/LastCSA14/ChargedHadronPtComp25_50.png')
#can1.Print('/afs/hephy.at/user/e/easilar/www/LastCSA14/ChargedHadronPtComp25_50Pdg13.png')
#can1.Delete()
#leg1 = ROOT.TLegend(0.1,0.7,0.48,0.9)
#leg1.AddEntry(h_RelIso50, "50ns")
#leg1.AddEntry(h_RelIso25, "25ns")
#leg1.Draw()
can1.Write()
#can1.Close()

can2 = ROOT.TCanvas('NeutralHadronEt Comp 50_25')
can2.cd()
h_NeutralHadronEt25.SetLineColor(ROOT.kBlue)
h_NeutralHadronEt25.Draw()
h_NeutralHadronEt50.SetLineColor(ROOT.kRed)
h_NeutralHadronEt50.SetLineWidth(2)
h_NeutralHadronEt50.Draw('same')
#can2.SetLogy()
#can2.Print('/afs/hephy.at/user/e/easilar/www/LastCSA14/NeutralHadronEt25_50.png')
#can2.Print('/afs/hephy.at/user/e/easilar/www/LastCSA14/NeutralHadronEtComp25_50Pdg13.png')
#can2.Delete()
can2.Write()
#can2.Close()

can3 = ROOT.TCanvas('PhotonEt Comp 50_25')
can3.cd()
h_PhotonEt50.SetLineColor(ROOT.kRed)
h_PhotonEt50.SetLineWidth(2)
h_PhotonEt50.Draw()
h_PhotonEt25.SetLineColor(ROOT.kBlue)
h_PhotonEt25.Draw('same')
#can3.SetLogy()
#can3.Print('/afs/hephy.at/user/e/easilar/www/LastCSA14/PhotonEt25_50.png')
#can3.Print('/afs/hephy.at/user/e/easilar/www/LastCSA14/PhotonEtComp25_50Pdg13.png')
#can3.Delete()
can3.Write()
#can3.Close()

can4 = ROOT.TCanvas('PUChargedHadronPt Comp 50_25')
can4.cd()
h_PUChargedHadronPt25.SetLineColor(ROOT.kBlue)
h_PUChargedHadronPt25.Draw()
h_PUChargedHadronPt50.SetLineColor(ROOT.kRed)
h_PUChargedHadronPt50.SetLineWidth(2)
h_PUChargedHadronPt50.Draw('same')
#can4.SetLogy()
#can4.Print('/afs/hephy.at/user/e/easilar/www/LastCSA14/PUChargedHadronPt25_50.png')
#can4.Print('/afs/hephy.at/user/e/easilar/www/LastCSA14/PUChargedHadronPtComp25_50Pdg13.png')
#can4.Delete()
can4.Write()
#can4.Close()

can5 = ROOT.TCanvas('RelIso Comp Calculated&Direct for 25ns')
can5.cd()
h_RelIso25.SetLineColor(ROOT.kBlue)
h_RelIso25.Draw()
h_RelIso25Pred.SetLineColor(ROOT.kRed)
h_RelIso25Pred.SetLineWidth(2)
h_RelIso25Pred.Draw('same')
#can.SetLogy()
#can5.Print('/afs/hephy.at/user/e/easilar/www/LastCSA14/MuonRelIso50comp_Pred_Full.png')
#can5.Print('/afs/hephy.at/user/e/easilar/www/LastCSA14/MuonRelIso25Pred_realComp.png')
#can5.Delete()
can5.Write()
#can5.Close()

can6 = ROOT.TCanvas('RelIso Comp Calculated&Direct for 50ns')
can6.cd()
h_RelIso50.SetLineColor(ROOT.kRed) 
h_RelIso50.Scale(1/h_RelIso50.Integral())
h_RelIso50.SetLineWidth(2)
h_RelIso50.Draw()
h_RelIso50Pred.SetLineColor(ROOT.kBlue)
h_RelIso50Pred.SetLineWidth(2)
h_RelIso50Pred.Draw('same')
can6.Write()
#can6.Close()

can7 = ROOT.TCanvas('Four Iso for 50ns')
can7.cd()
h_ChargedHadronPt50.SetLineColor(ROOT.kBlue)
h_ChargedHadronPt50.Draw()
h_NeutralHadronEt50.SetLineColor(ROOT.kRed)
h_NeutralHadronEt50.Draw('same')
h_PhotonEt50.SetLineColor(ROOT.kGreen)
h_PhotonEt50.Draw('same')
h_PUChargedHadronPt50.SetLineColor(ROOT.kYellow)
h_PUChargedHadronPt50.Draw('same')
leg7 = ROOT.TLegend(0.6,0.6,0.9,0.7)
leg7.AddEntry(h_ChargedHadronPt50, "h_ChargedHadronPt50","l")
leg7.AddEntry(h_NeutralHadronEt50, "h_NeutralHadronEt50","l")
leg7.AddEntry(h_PhotonEt50, "h_PhotonEt5","l")
leg7.AddEntry(h_PUChargedHadronPt50, "h_PUChargedHadronPt50","l")
leg7.SetFillColor(0)
leg7.Draw()
can.Update()
can.Write()
can7.Write()
#can7.Close()

can8 = ROOT.TCanvas('Four Iso for 25ns')
can8.cd()
h_ChargedHadronPt25.SetLineColor(ROOT.kBlue)
h_ChargedHadronPt25.Draw()
h_NeutralHadronEt25.SetLineColor(ROOT.kRed)
h_NeutralHadronEt25.Draw('same')
h_PhotonEt25.SetLineColor(ROOT.kGreen)
h_PhotonEt25.Draw('same')
h_PUChargedHadronPt25.SetLineColor(ROOT.kYellow)
h_PUChargedHadronPt25.Draw('same')
leg8 = ROOT.TLegend(0.6,0.6,0.9,0.7)
leg8.AddEntry(h_ChargedHadronPt25, "h_ChargedHadronPt25","l")
leg8.AddEntry(h_NeutralHadronEt25, "h_NeutralHadronEt25","l")
leg8.AddEntry(h_PhotonEt25, "h_PhotonEt25","l")
leg8.AddEntry(h_PUChargedHadronPt25, "h_PUChargedHadronPt25","l")
leg8.SetFillColor(0)
leg8.Draw()
can.Update()
can.Write()
can8.Write()

File.Write()
File.Close()

