python makePrediction.py --SR "Moriond" --nSR 0
python makePrediction.py --SR "Moriond" --nSR 1
python makePrediction.py --SR "Moriond" --nSR 2
python makePrediction.py --SR "Moriond" --nSR 3
python makePrediction.py --SR "Moriond" --nSR 4
python makePrediction.py --SR "Moriond" --nSR 5
python makePrediction.py --SR "Moriond" --nSR 6
python makePrediction.py --SR "Moriond" --nSR 7
python makePrediction.py --SR "Moriond" --nSR 8
python makePrediction.py --SR "Moriond" --nSR 9
python makePrediction.py --SR "Moriond" --nSR 10
python makePrediction.py --SR "Moriond" --nSR 11
python makePrediction.py --SR "Moriond" --nSR 12
python makePrediction.py --SR "Moriond" --nSR 13
python makePrediction.py --SR "Moriond" --nSR 14
python makePrediction.py --SR "Moriond" --nSR 15
python makePrediction.py --SR "Moriond" --nSR 16
python makePrediction.py --SR "Moriond" --nSR 17
python makePrediction.py --SR "Moriond" --nSR 18
python makePrediction.py --SR "Moriond" --nSR 19
python makePrediction.py --SR "Moriond" --nSR 20
python makePrediction.py --SR "Moriond" --nSR 21
python makePrediction.py --SR "Moriond" --nSR 22
python makePrediction.py --SR "Moriond" --nSR 23
python makePrediction.py --SR "Moriond" --nSR 24
python makePrediction.py --SR "Moriond" --nSR 25
python makePrediction.py --SR "Moriond" --nSR 26
python makePrediction.py --SR "Moriond" --nSR 27
