python makePrediction.py --nSR 0
python makePrediction.py --nSR 1
python makePrediction.py --nSR 2
python makePrediction.py --nSR 3
python makePrediction.py --nSR 4
python makePrediction.py --nSR 5
python makePrediction.py --nSR 6
python makePrediction.py --nSR 7
python makePrediction.py --nSR 8
python makePrediction.py --nSR 9
python makePrediction.py --nSR 10
python makePrediction.py --nSR 11
python makePrediction.py --nSR 12
python makePrediction.py --nSR 13
python makePrediction.py --nSR 14
python makePrediction.py --nSR 15
python makePrediction.py --nSR 16
python makePrediction.py --nSR 17
python makePrediction.py --nSR 18
python makePrediction.py --nSR 19
python makePrediction.py --nSR 20
#python makePrediction.py --nSR 21
#python makePrediction.py --nSR 22
#python makePrediction.py --nSR 23
#python makePrediction.py --nSR 24
#python makePrediction.py --nSR 25
#python makePrediction.py --nSR 26
#python makePrediction.py --nSR 27
