#! /bin/sh -x 

mkdir -p /data/$1/$3

for name in `dpns-ls /dpm/oeaw.ac.at/home/cms/store/user/$1/$2`
do
   $LCG_LOCATION/bin/dpm/rfcp /dpm/oeaw.ac.at/home/cms/store/user/$1/$2/$name /data/$1/$3/$name 
done
#/scratch/$1/$3/$name
