#! /bin/sh -x 
#for name in `ls -d 8TeV-WJetsToLNu_HT-* 8TeV*TTJets*`
#for name in `ls -d 8TeV-Wplus* 8TeV-Wminus* 8TeV-WJetsToLNu_HT-*`
for name in `ls -d *LeptMGDecays*`
do
  tokens
  crab $1 $2 -c $name 
done
