python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=lep  --sigOpt=all  --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights sf prompt pu isr_tt  wpt trig_eff lepsffix  --cut=bins_mtct_sum    ""         --postFuncs=fakeEstimate
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=el   --sigOpt=all  --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights sf prompt pu isr_tt  wpt trig_eff lepsffix  --cut=bins_mtct_sum    ""         
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=mu   --sigOpt=all  --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights sf prompt pu isr_tt  wpt trig_eff lepsffix  --cut=bins_mtct_sum    ""        
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=lep  --sigOpt=bm   --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights sf prompt pu isr_tt  trig_eff lepsffix  --cut=bins_mtct_sum    ""         --postFuncs=fakeEstimate
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=el   --sigOpt=bm   --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights sf prompt pu isr_tt  trig_eff lepsffix  --cut=bins_mtct_sum    ""         
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=mu   --sigOpt=bm   --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights sf prompt pu isr_tt  trig_eff lepsffix  --cut=bins_mtct_sum    ""        
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=lep  --sigOpt=bm   --bkgs ttx vv qcd st z dy tt_1l tt_2l w  --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights sf prompt pu  wpt trig_eff lepsffix  --cut=bins_mtct_sum    ""         --postFuncs=fakeEstimate
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=el   --sigOpt=bm   --bkgs ttx vv qcd st z dy tt_1l tt_2l w  --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights sf prompt pu  wpt trig_eff lepsffix  --cut=bins_mtct_sum    ""         
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=mu   --sigOpt=bm   --bkgs ttx vv qcd st z dy tt_1l tt_2l w  --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights sf prompt pu  wpt trig_eff lepsffix  --cut=bins_mtct_sum    ""        
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=lep  --sigOpt=bm   --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights sf prompt pu_down  isr_tt wpt trig_eff lepsffix  --cut=bins_mtct_sum    ""         --postFuncs=fakeEstimate 
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=el   --sigOpt=bm   --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights sf prompt pu_down  isr_tt wpt trig_eff lepsffix  --cut=bins_mtct_sum    ""         
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=mu   --sigOpt=bm   --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights sf prompt pu_down  isr_tt wpt trig_eff lepsffix  --cut=bins_mtct_sum    ""         
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=lep  --sigOpt=bm   --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights sf prompt pu_up  isr_tt wpt trig_eff lepsffix  --cut=bins_mtct_sum    ""         --postFuncs=fakeEstimate 
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=el   --sigOpt=bm   --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights sf prompt pu_up  isr_tt wpt trig_eff lepsffix  --cut=bins_mtct_sum    ""        
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=mu   --sigOpt=bm   --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights sf prompt pu_up  isr_tt wpt trig_eff lepsffix  --cut=bins_mtct_sum    ""        
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=lep  --sigOpt=all  --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights sf_l_down prompt pu  isr_tt wpt trig_eff lepsffix  --cut=bins_mtct_sum    ""         --postFuncs=fakeEstimate 
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=el   --sigOpt=all  --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights sf_l_down prompt pu  isr_tt wpt trig_eff lepsffix  --cut=bins_mtct_sum    ""        
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=mu   --sigOpt=all  --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights sf_l_down prompt pu  isr_tt wpt trig_eff lepsffix  --cut=bins_mtct_sum    ""        
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=lep  --sigOpt=all  --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights sf_l_up prompt pu  isr_tt wpt trig_eff lepsffix  --cut=bins_mtct_sum    ""          --postFuncs=fakeEstimate 
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=el   --sigOpt=all  --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights sf_l_up prompt pu  isr_tt wpt trig_eff lepsffix  --cut=bins_mtct_sum    ""        
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=mu   --sigOpt=all  --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights sf_l_up prompt pu  isr_tt wpt trig_eff lepsffix  --cut=bins_mtct_sum    ""        
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=lep  --sigOpt=all  --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights sf_b_down prompt pu  isr_tt wpt trig_eff lepsffix  --cut=bins_mtct_sum    ""          --postFuncs=fakeEstimate
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=el   --sigOpt=all  --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights sf_b_down prompt pu  isr_tt wpt trig_eff lepsffix  --cut=bins_mtct_sum    ""        
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=mu   --sigOpt=all  --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights sf_b_down prompt pu  isr_tt wpt trig_eff lepsffix  --cut=bins_mtct_sum    ""        
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=lep  --sigOpt=all  --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights sf_b_up prompt pu  isr_tt wpt trig_eff lepsffix  --cut=bins_mtct_sum    ""          --postFuncs=fakeEstimate
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=el   --sigOpt=all  --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights sf_b_up prompt pu  isr_tt wpt trig_eff lepsffix  --cut=bins_mtct_sum    ""        
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=mu   --sigOpt=all  --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights sf_b_up prompt pu  isr_tt wpt trig_eff lepsffix  --cut=bins_mtct_sum    ""        

python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=lep  --sigOpt=all  --bkgs vv --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights noisrsig sf prompt pu isr_tt  wpt trig_eff lepsffix  --cut=bins_mtct_sum    ""         --postFuncs=fakeEstimate
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=el   --sigOpt=all  --bkgs vv --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights noisrsig sf prompt pu isr_tt  wpt trig_eff lepsffix  --cut=bins_mtct_sum    ""         
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=mu   --sigOpt=all  --bkgs vv --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights noisrsig sf prompt pu isr_tt  wpt trig_eff lepsffix  --cut=bins_mtct_sum    ""        
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=lep  --sigOpt=all  --bkgs vv --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights sf_fs_up prompt pu isr_tt  wpt trig_eff lepsffix  --cut=bins_mtct_sum    ""         --postFuncs=fakeEstimate
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=el   --sigOpt=all  --bkgs vv --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights sf_fs_up prompt pu isr_tt  wpt trig_eff lepsffix  --cut=bins_mtct_sum    ""         
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=mu   --sigOpt=all  --bkgs vv --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights sf_fs_up prompt pu isr_tt  wpt trig_eff lepsffix  --cut=bins_mtct_sum    ""        
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=lep  --sigOpt=all  --bkgs vv --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights sf_fs_down prompt pu isr_tt  wpt trig_eff lepsffix  --cut=bins_mtct_sum    ""         --postFuncs=fakeEstimate
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=el   --sigOpt=all  --bkgs vv --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights sf_fs_down prompt pu isr_tt  wpt trig_eff lepsffix  --cut=bins_mtct_sum    ""         
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=mu   --sigOpt=all  --bkgs vv --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights sf_fs_down prompt pu isr_tt  wpt trig_eff lepsffix  --cut=bins_mtct_sum    ""       
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=lep  --sigOpt=all  --bkgs vv --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights genmet sf prompt pu isr_tt  wpt trig_eff lepsffix  --cut=bins_mtct_sum    ""         --postFuncs=fakeEstimate
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=el   --sigOpt=all  --bkgs vv --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights genmet sf prompt pu isr_tt  wpt trig_eff lepsffix  --cut=bins_mtct_sum    ""         
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=mu   --sigOpt=all  --bkgs vv --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights genmet sf prompt pu isr_tt  wpt trig_eff lepsffix  --cut=bins_mtct_sum    ""        

python  degStop.py -- --cfg=EPS17_v0 --task=yields --skim=filterMETHT250 ""   --lepCol=LepGood --lep=lep --sigOpt=all  --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data="" --weights sf prompt pu  isr_tt wpt trig_eff lepsffix jec_up --cut=bins_mtct_sum   ""   --postFuncs=fakeEstimate
python  degStop.py -- --cfg=EPS17_v0 --task=yields --skim=filterMETHT250 ""   --lepCol=LepGood --lep=el  --sigOpt=all  --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data="" --weights sf prompt pu  isr_tt wpt trig_eff lepsffix jec_up --cut=bins_mtct_sum   "" 
python  degStop.py -- --cfg=EPS17_v0 --task=yields --skim=filterMETHT250 ""   --lepCol=LepGood --lep=mu  --sigOpt=all  --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data="" --weights sf prompt pu  isr_tt wpt trig_eff lepsffix jec_up --cut=bins_mtct_sum   "" 
python  degStop.py -- --cfg=EPS17_v0 --task=yields --skim=filterMETHT250 ""   --lepCol=LepGood --lep=lep --sigOpt=all  --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data="" --weights sf prompt pu  isr_tt wpt trig_eff lepsffix jec_down --cut=bins_mtct_sum   ""   --postFuncs=fakeEstimate
python  degStop.py -- --cfg=EPS17_v0 --task=yields --skim=filterMETHT250 ""   --lepCol=LepGood --lep=el  --sigOpt=all  --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data="" --weights sf prompt pu  isr_tt wpt trig_eff lepsffix jec_down --cut=bins_mtct_sum   "" 
python  degStop.py -- --cfg=EPS17_v0 --task=yields --skim=filterMETHT250 ""   --lepCol=LepGood --lep=mu  --sigOpt=all  --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data="" --weights sf prompt pu  isr_tt wpt trig_eff lepsffix jec_down --cut=bins_mtct_sum   "" 
python  degStop.py -- --cfg=EPS17_v0 --task=yields --skim=filterMETHT250 ""   --lepCol=LepGood --lep=lep --sigOpt=all  --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data="" --weights sf prompt pu  isr_tt wpt trig_eff lepsffix jec_central --cut=bins_mtct_sum   ""   --postFuncs=fakeEstimate
python  degStop.py -- --cfg=EPS17_v0 --task=yields --skim=filterMETHT250 ""   --lepCol=LepGood --lep=el  --sigOpt=all  --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data="" --weights sf prompt pu  isr_tt wpt trig_eff lepsffix jec_central --cut=bins_mtct_sum   "" 
python  degStop.py -- --cfg=EPS17_v0 --task=yields --skim=filterMETHT250 ""   --lepCol=LepGood --lep=mu  --sigOpt=all  --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data="" --weights sf prompt pu  isr_tt wpt trig_eff lepsffix jec_central --cut=bins_mtct_sum   "" 
python  degStop.py -- --cfg=EPS17_v0 --task=yields --skim=filterMETHT250 ""   --lepCol=LepGood --lep=lep --sigOpt=all  --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data="" --weights sf prompt pu  isr_tt wpt trig_eff lepsffix jer_up --cut=bins_mtct_sum   ""   --postFuncs=fakeEstimate
python  degStop.py -- --cfg=EPS17_v0 --task=yields --skim=filterMETHT250 ""   --lepCol=LepGood --lep=el  --sigOpt=all  --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data="" --weights sf prompt pu  isr_tt wpt trig_eff lepsffix jer_up --cut=bins_mtct_sum   "" 
python  degStop.py -- --cfg=EPS17_v0 --task=yields --skim=filterMETHT250 ""   --lepCol=LepGood --lep=mu  --sigOpt=all  --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data="" --weights sf prompt pu  isr_tt wpt trig_eff lepsffix jer_up --cut=bins_mtct_sum   "" 
python  degStop.py -- --cfg=EPS17_v0 --task=yields --skim=filterMETHT250 ""   --lepCol=LepGood --lep=lep --sigOpt=all  --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data="" --weights sf prompt pu  isr_tt wpt trig_eff lepsffix jer_down --cut=bins_mtct_sum   ""   --postFuncs=fakeEstimate
python  degStop.py -- --cfg=EPS17_v0 --task=yields --skim=filterMETHT250 ""   --lepCol=LepGood --lep=el  --sigOpt=all  --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data="" --weights sf prompt pu  isr_tt wpt trig_eff lepsffix jer_down --cut=bins_mtct_sum   "" 
python  degStop.py -- --cfg=EPS17_v0 --task=yields --skim=filterMETHT250 ""   --lepCol=LepGood --lep=mu  --sigOpt=all  --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data="" --weights sf prompt pu  isr_tt wpt trig_eff lepsffix jer_down --cut=bins_mtct_sum   "" 
python  degStop.py -- --cfg=EPS17_v0 --task=yields --skim=filterMETHT250 ""   --lepCol=LepGood --lep=lep --sigOpt=all  --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data="" --weights sf prompt pu  isr_tt wpt trig_eff lepsffix jer_central --cut=bins_mtct_sum   ""   --postFuncs=fakeEstimate
python  degStop.py -- --cfg=EPS17_v0 --task=yields --skim=filterMETHT250 ""   --lepCol=LepGood --lep=el  --sigOpt=all  --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data="" --weights sf prompt pu  isr_tt wpt trig_eff lepsffix jer_central --cut=bins_mtct_sum   "" 
python  degStop.py -- --cfg=EPS17_v0 --task=yields --skim=filterMETHT250 ""   --lepCol=LepGood --lep=mu  --sigOpt=all  --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=20  --jetThresh=def   --lepThresh=lowpt   --data="" --weights sf prompt pu  isr_tt wpt trig_eff lepsffix jer_central --cut=bins_mtct_sum   "" 

