python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=lep  --sigOpt=all  --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=10  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights STXSECFIX sf prompt pu isr_tt  wpt trig_eff lepsffix  --cut=bins_mtct_sum   --redo_yields  --postFuncs=fakeEstimate
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=el   --sigOpt=all  --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=10  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights STXSECFIX sf prompt pu isr_tt  wpt trig_eff lepsffix  --cut=bins_mtct_sum   --redo_yields  
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=mu   --sigOpt=all  --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=10  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights STXSECFIX sf prompt pu isr_tt  wpt trig_eff lepsffix  --cut=bins_mtct_sum   --redo_yields 
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=lep  --sigOpt=bm   --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=10  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights STXSECFIX sf prompt pu isr_tt  trig_eff lepsffix  --cut=bins_mtct_sum   --redo_yields  --postFuncs=fakeEstimate
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=el   --sigOpt=bm   --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=10  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights STXSECFIX sf prompt pu isr_tt  trig_eff lepsffix  --cut=bins_mtct_sum   --redo_yields  
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=mu   --sigOpt=bm   --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=10  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights STXSECFIX sf prompt pu isr_tt  trig_eff lepsffix  --cut=bins_mtct_sum   --redo_yields 
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=lep  --sigOpt=bm   --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=10  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights STXSECFIX sf prompt pu  wpt trig_eff lepsffix  --cut=bins_mtct_sum   --redo_yields  --postFuncs=fakeEstimate
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=el   --sigOpt=bm   --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=10  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights STXSECFIX sf prompt pu  wpt trig_eff lepsffix  --cut=bins_mtct_sum   --redo_yields  
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=mu   --sigOpt=bm   --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=10  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights STXSECFIX sf prompt pu  wpt trig_eff lepsffix  --cut=bins_mtct_sum   --redo_yields 
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=lep  --sigOpt=bm   --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=10  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights STXSECFIX sf prompt pu_down  isr_tt wpt trig_eff lepsffix  --cut=bins_mtct_sum   --redo_yields  --postFuncs=fakeEstimate 
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=el   --sigOpt=bm   --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=10  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights STXSECFIX sf prompt pu_down  isr_tt wpt trig_eff lepsffix  --cut=bins_mtct_sum   --redo_yields  
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=mu   --sigOpt=bm   --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=10  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights STXSECFIX sf prompt pu_down  isr_tt wpt trig_eff lepsffix  --cut=bins_mtct_sum   --redo_yields  
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=lep  --sigOpt=bm   --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=10  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights STXSECFIX sf prompt pu_up  isr_tt wpt trig_eff lepsffix  --cut=bins_mtct_sum   --redo_yields  --postFuncs=fakeEstimate 
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=el   --sigOpt=bm   --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=10  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights STXSECFIX sf prompt pu_up  isr_tt wpt trig_eff lepsffix  --cut=bins_mtct_sum   --redo_yields 
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=mu   --sigOpt=bm   --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=10  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights STXSECFIX sf prompt pu_up  isr_tt wpt trig_eff lepsffix  --cut=bins_mtct_sum   --redo_yields 
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=lep  --sigOpt=all  --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=10  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights STXSECFIX sf_l_down prompt pu  isr_tt wpt trig_eff lepsffix  --cut=bins_mtct_sum   --redo_yields  --postFuncs=fakeEstimate 
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=el   --sigOpt=all  --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=10  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights STXSECFIX sf_l_down prompt pu  isr_tt wpt trig_eff lepsffix  --cut=bins_mtct_sum   --redo_yields 
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=mu   --sigOpt=all  --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=10  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights STXSECFIX sf_l_down prompt pu  isr_tt wpt trig_eff lepsffix  --cut=bins_mtct_sum   --redo_yields 
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=lep  --sigOpt=all  --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=10  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights STXSECFIX sf_l_up prompt pu  isr_tt wpt trig_eff lepsffix  --cut=bins_mtct_sum   --redo_yields   --postFuncs=fakeEstimate 
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=el   --sigOpt=all  --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=10  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights STXSECFIX sf_l_up prompt pu  isr_tt wpt trig_eff lepsffix  --cut=bins_mtct_sum   --redo_yields 
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=mu   --sigOpt=all  --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=10  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights STXSECFIX sf_l_up prompt pu  isr_tt wpt trig_eff lepsffix  --cut=bins_mtct_sum   --redo_yields 
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=lep  --sigOpt=all  --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=10  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights STXSECFIX sf_b_down prompt pu  isr_tt wpt trig_eff lepsffix  --cut=bins_mtct_sum   --redo_yields   --postFuncs=fakeEstimate
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=el   --sigOpt=all  --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=10  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights STXSECFIX sf_b_down prompt pu  isr_tt wpt trig_eff lepsffix  --cut=bins_mtct_sum   --redo_yields 
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=mu   --sigOpt=all  --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=10  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights STXSECFIX sf_b_down prompt pu  isr_tt wpt trig_eff lepsffix  --cut=bins_mtct_sum   --redo_yields 
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=lep  --sigOpt=all  --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=10  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights STXSECFIX sf_b_up prompt pu  isr_tt wpt trig_eff lepsffix  --cut=bins_mtct_sum   --redo_yields   --postFuncs=fakeEstimate
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=el   --sigOpt=all  --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=10  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights STXSECFIX sf_b_up prompt pu  isr_tt wpt trig_eff lepsffix  --cut=bins_mtct_sum   --redo_yields 
python  degStop.py -- --cfg=EPS17_v0 --task=yields  --skim=filterMETHT250 ""  --lepCol=LepGood --lep=mu   --sigOpt=all  --bkgs ttx vv qcd st z dy tt_1l tt_2l w --nProc=10  --jetThresh=def   --lepThresh=lowpt   --data=dblind --weights STXSECFIX sf_b_up prompt pu  isr_tt wpt trig_eff lepsffix  --cut=bins_mtct_sum   --redo_yields 
